version: '3.8'

services:
  backend:
    image: node:18
    container_name: amazon-clone-backend
    working_dir: /app
    volumes:
      - .:/app
    command: ["npm", "start"]
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: node:18
    container_name: amazon-clone-frontend
    working_dir: /app/client
    volumes:
      - .:/app
    command: ["/bin/sh", "-c", "npm install && npm start"]
    ports:
      - "3000:3000"
    restart: always
